version: '3.5'
volumes:
  db: {name: 'sfes_db'}

services:
  db:
    container_name: 'sfes_db'
    image: 'mariadb:11.0.2'
    ports: [ '33006:3306/tcp' ]
    volumes:
      - 'db:/var/lib/mysql/'
    environment: ['TZ=UTC', 'MYSQL_DATABASE=sfes', 'MYSQL_ROOT_PASSWORD=mypass']
    restart: no

